<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DshTray</AssemblyName>
    <RootNamespace>DshTray</RootNamespace>
    <ApplicationIcon>deepseek.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="deepseek.ico" LogicalName="DshTray.deepseek.ico" />
  </ItemGroup>

</Project>
